repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: flake8
    - repo: https://github.com/ambv/black
      rev: stable
      hooks:
          - id: black
    - repo: https://github.com/prettier/prettier
      rev: 1.19.1
      hooks:
          - id: prettier
